import type { Mentor } from './types';
import images from './placeholder-images.json';

export const MENTORS_DATA: Mentor[] = [
  {
    id: '1',
    name: 'Aisha Sharma',
    imageUrl: images.mentors.aisha.src,
    dataAiHint: images.mentors.aisha.dataAiHint,
    qualifications: ['Certified Tour Guide', 'Wilderness First Responder'],
    experience: '10+ years in eco-tourism',
    expertise: ['Wildlife Safaris', 'Hiking', 'Cultural Immersion'],
    location: 'Cape Town',
    bio: 'Passionate about sharing the natural beauty and rich culture of South Africa. Specializes in sustainable travel and ensuring every traveler feels safe and inspired.',
    languages: ['English', 'Afrikaans', 'Xhosa'],
  },
  {
    id: '2',
    name: 'Bongani Mthembu',
    imageUrl: images.mentors.bongani.src,
    dataAiHint: images.mentors.bongani.dataAiHint,
    qualifications: ['Adventure Guide Level 3', 'Advanced Driving'],
    experience: '8 years guiding adventure tours',
    expertise: ['Mountain Biking', 'Rock Climbing', 'Community Projects'],
    location: 'Drakensberg',
    bio: 'An adrenaline junkie with a love for the mountains and a commitment to uplifting local communities. Expert in off-the-beaten-path adventures.',
    languages: ['English', 'Zulu'],
  },
  {
    id: '3',
    name: 'Sarah Chen',
    imageUrl: images.mentors.sarah.src,
    dataAiHint: images.mentors.sarah.dataAiHint,
    qualifications: ['Culinary Arts Degree', 'Local History Expert'],
    experience: '5 years in food and heritage tours',
    expertise: ['Food Tours', 'Historical Walks', 'Artisan Crafts'],
    location: 'Johannesburg',
    bio: 'Discover the vibrant culinary scene and rich history of Jozi with a local foodie. Passionate about storytelling through food and culture.',
    languages: ['English', 'Mandarin'],
  },
  {
    id: '4',
    name: 'David Miller',
    imageUrl: images.mentors.david.src,
    dataAiHint: images.mentors.david.dataAiHint,
    qualifications: ['Marine Biology BSc', 'Divemaster Certified'],
    experience: '12 years in marine conservation and tourism',
    expertise: ['Scuba Diving', 'Shark Cage Diving', 'Coastal Ecology'],
    location: 'Durban',
    bio: 'Explore the incredible marine biodiversity of the KZN coast. Dedicated to ocean conservation and providing thrilling, safe underwater experiences.',
    languages: ['English', 'Afrikaans'],
  },
   {
    id: '5',
    name: 'Naledi Kgotso',
    imageUrl: images.mentors.naledi.src,
    dataAiHint: images.mentors.naledi.dataAiHint,
    qualifications: ['FGASA Level 2', 'Photography Guide'],
    experience: '7 years as a safari guide in Kruger National Park',
    expertise: ['Big 5 Safaris', 'Bird Watching', 'Wildlife Photography'],
    location: 'Kruger National Park Area',
    bio: 'An expert tracker and passionate photographer, Naledi offers immersive safari experiences, helping you capture unforgettable moments.',
    languages: ['English', 'Tswana', 'Sotho'],
  },
  {
    id: '6',
    name: 'Pieter van der Merwe',
    imageUrl: images.mentors.pieter.src,
    dataAiHint: images.mentors.pieter.dataAiHint,
    qualifications: ['Cape Wine Master Candidate', 'Hospitality Management'],
    experience: '9 years in the Winelands tourism sector',
    expertise: ['Wine Tasting Tours', 'Gourmet Experiences', 'Boutique Vineyards'],
    location: 'Stellenbosch',
    bio: 'Indulge in the finest wines and culinary delights of the Cape Winelands. Pieter crafts bespoke tours for oenophiles and food lovers alike.',
    languages: ['English', 'Afrikaans'],
  },
];
