import Link from 'next/link';
import { Button } from '@/components/ui/button';
export const metadata = { title: 'Fragen & Antworten · Stay Safe & Brave' };
const questions = [
  ['Was kann ich in der Demo ausprobieren?', 'Du wählst ein fiktives Mentorprofil und eines von drei Paketen, ergänzt Reisedaten und legst die Auswahl in den Warenkorb. Danach kannst du eine erfolgreiche, abgelehnte oder abgebrochene Zahlung testen. Nach Erfolg erhältst du eine Demo-Bestätigung und eine Reiseübersicht.'],
  ['Wird dabei wirklich Geld abgebucht?', 'Nein. Die Demo fragt keine Bank- oder Kartendaten ab und kontaktiert keinen Zahlungsdienst. 95 €, 195 € und 295 € sind fiktive Beispielpreise. Die Simulation löst keine echte Buchung aus.'],
  ['Sind die Mentorprofile echt und verfügbar?', 'Die neun ausdrücklich als Beispielprofile gekennzeichneten Personenbeschreibungen sind fiktiv. Die Demo macht keine Aussage über reale Verfügbarkeit oder Verifizierung. Weitere Profile erscheinen auf der Mentorenseite getrennt von diesen Beispielen.'],
  ['Erhalte ich eine E-Mail oder Antwort von einem Mentor?', 'In der Demo erscheint eine Bestätigung als Nachrichtenvorschau direkt auf der Website. Es wird keine E-Mail verschickt. Chatantworten sind vorformuliert; Terminwünsche werden nur lokal vorgemerkt.'],
  ['Brauche ich ein Konto?', 'Für die Demo nicht. Sie speichert ihren Fortschritt im Browser auf diesem Gerät. Verwende Beispieldaten. Über „Neu beginnen“ im Demo-Bereich kannst du den Durchlauf zurücksetzen. Bei gesperrtem Browserspeicher funktioniert die Demo nur bis zum Neuladen.'],
  ['Was unterscheidet die Pakete?', 'Basis dient der Vorbereitung und dem ersten Austausch. Standard ergänzt Unterstützung beim Ankommen. Premium erweitert die persönliche Begleitung. Den genauen Demo-Leistungsumfang findest du im Paketvergleich. Reale Leistungen und Konditionen müssen separat abgestimmt werden.'],
  ['Organisiert Stay Safe & Brave meine gesamte Reise?', 'Du planst deine Reise selbst. Das Konzept ergänzt sie durch einen persönlichen lokalen Kontakt. Die Demo bucht weder Flüge noch Unterkunft, Transport oder Aktivitäten. Begleitung ist keine Sicherheitsgarantie.'],
  ['Was ist außerhalb der Demo möglich?', 'Du kannst öffentliche Inhalte ansehen und bei tatsächlich verfügbaren Profilen den bestehenden Anfrageprozess nutzen. Eine Anfrage ist noch keine bestätigte Buchung. Die Demo aktiviert keine realen Online-Zahlungen.'],
];
export default function FAQ() { return <div className="page-shell max-w-4xl py-12"><p className="eyebrow mb-4">Gut zu wissen</p><h1 className="editorial-title page-title">Fragen zu Stay Safe & Brave.</h1><p className="mt-5 text-lg text-muted-foreground">Antworten zum Angebot und zur interaktiven Demo.</p><div className="my-9">{questions.map(([q,a]) => <details key={q} className="border-b py-5"><summary className="cursor-pointer pr-3 font-medium">{q}</summary><p className="mt-4 text-sm leading-relaxed text-muted-foreground">{a}</p></details>)}</div><div className="flex flex-wrap gap-4"><Button asChild><Link href="/demo">Demo ausprobieren</Link></Button><Button asChild variant="outline"><Link href="/kontakt">Fragen an unser Team</Link></Button></div></div>; }
