const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const ts=require('typescript');const crypto=require('node:crypto');const Stripe=require('stripe');
function loader(mocks={}){const cache=new Map();function load(file){file=path.resolve(file);if(cache.has(file))return cache.get(file).exports;const module={exports:{}};cache.set(file,module);const req=(name)=>{if(name in mocks)return mocks[name];let target=name.startsWith('@/')?path.join(__dirname,'../src',name.slice(2)):name.startsWith('.')?path.resolve(path.dirname(file),name):null;if(target)return load(target.endsWith('.ts')?target:target+'.ts');return require(name);};new Function('require','module','exports',ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText)(req,module,module.exports);return module.exports;}return load;}
function fakeDB(){const data=new Map();let chain=Promise.resolve();const snapshot=(key)=>({exists:data.has(key),data:()=>data.has(key)?structuredClone(data.get(key)):undefined,id:key.split('/').pop()});function ref(key){return {path:key,get:async()=>snapshot(key),set:async value=>data.set(key,structuredClone(value)),update:async value=>data.set(key,{...data.get(key),...value}),collection:name=>collection(key+'/'+name)};}function collection(key){return {doc:id=>ref(key+'/'+id)};}return {data,collection,runTransaction(fn){const result=chain.then(async()=>{let wrote=false;const ops=[];const tx={get:async r=>{assert.equal(wrote,false,'transaction reads must precede writes');return snapshot(r.path);},set:(r,v)=>{wrote=true;ops.push(()=>data.set(r.path,structuredClone(v)));},create:(r,v)=>{wrote=true;ops.push(()=>{assert.ok(!data.has(r.path));data.set(r.path,structuredClone(v));});},update:(r,v)=>{wrote=true;ops.push(()=>data.set(r.path,{...data.get(r.path),...structuredClone(v)}));}};const out=await fn(tx);ops.forEach(f=>f());return out;});chain=result.catch(()=>{});return result;}};}
function fixture(){const db=fakeDB();class ApiError extends Error{constructor(status,message){super(message);this.status=status;}}const admin={admin:()=>({db}),ApiError,serverReady:()=>true,siteURL:()=> 'https://example.test',rateLimit:async()=>{},jsonBody:req=>req.json(),fail:e=>Response.json({error:e.message},{status:e.status||500})};const sdk=new Stripe('sk_test_not_a_real_key');const sessions=new Map();let createCount=0,refundCount=0;const stripe={webhooks:sdk.webhooks,checkout:{sessions:{create:async(p,o)=>{if(sessions.has(o.idempotencyKey))return sessions.get(o.idempotencyKey);createCount++;const s={id:'cs_test_'+createCount,status:'open',url:'https://checkout.stripe.com/mock',...p};sessions.set(o.idempotencyKey,s);return s;},retrieve:async id=>[...sessions.values()].find(s=>s.id===id)}},refunds:{create:async()=>{refundCount++;return{id:'re_test_1'};}}};const mocks={'./admin':admin,'@/lib/server/admin':admin,'../stripe':{getStripe:()=>stripe},'@/lib/stripe':{getStripe:()=>stripe},'@/lib/server/outbox':{deliverOutbox:async()=>{}}};const load=loader(mocks);const model=load(path.join(__dirname,'../src/lib/commerce/model.ts'));const commerce=load(path.join(__dirname,'../src/lib/server/commerce.ts'));const offer={title:'Approved test offer',mentorId:'real-mentor-test',mentorName:'Approved Test Mentor',city:'Cape Town',amount:20000,currency:'eur',approved:true,profileVerified:true,termsVersion:'test-1',terms:'Fixture terms used only in isolated tests.',features:['Approved service']};db.data.set('commerceOffers/offer-1',offer);db.data.set('commerceSlots/slot-1',{offerId:'offer-1',arrival:'2099-01-10',departure:'2099-01-12',available:true});return {db,commerce,model,load,offer,sessions,get createCount(){return createCount;},get refundCount(){return refundCount;}};}
process.env.SSB_COMMERCE_ENABLED='true';process.env.STRIPE_SECRET_KEY='sk_test_not_a_real_key';process.env.STRIPE_WEBHOOK_SECRET='whsec_unit_test_only';process.env.SSB_SITE_URL='https://example.test';
const user={uid:'traveler-1',email:'anna@example.test',email_verified:true};const input=()=>({offerId:'offer-1',slotId:'slot-1',requestId:crypto.randomUUID(),acceptedTermsVersion:'test-1'});
test('client prices, unapproved offers and wrong terms cannot initiate payment',async()=>{const f=fixture();await assert.rejects(f.commerce.createCheckout(user,{...input(),amount:1}),e=>e.status===400);await assert.rejects(f.commerce.createCheckout(user,{...input(),acceptedTermsVersion:'old'}),e=>e.status===409);f.db.data.get('commerceOffers/offer-1').approved=false;await assert.rejects(f.commerce.createCheckout(user,input()),e=>e.status===409);assert.equal(f.createCount,0);});
test('repeat checkout reuses session; competing buyers and overlapping slots are rejected',async()=>{const f=fixture();const i=input();const a=await f.commerce.createCheckout(user,i);const b=await f.commerce.createCheckout(user,i);assert.equal(a.bookingId,b.bookingId);assert.equal(f.createCount,1);await assert.rejects(f.commerce.createCheckout({...user,uid:'other'},input()),e=>e.status===409);f.db.data.set('commerceSlots/slot-2',{offerId:'offer-1',arrival:'2099-01-11',departure:'2099-01-13',available:true});await assert.rejects(f.commerce.createCheckout(user,{...input(),slotId:'slot-2'}),e=>e.status===409);});
test('fictional profiles and malformed dates are never saleable',()=>{const f=fixture();assert.equal(f.model.offerSchema.safeParse({...f.offer,mentorId:'nomusa-ndlela'}).success,false);assert.throws(()=>f.model.datesForStay('2099-02-31','2099-03-01'));assert.throws(()=>f.model.datesForStay('2099-01-01','2099-03-01'));});
async function eventRequest(route,event,bad=false){const payload=JSON.stringify(event);const signature=Stripe.webhooks.generateTestHeaderString({payload,secret:bad?'wrong_secret':process.env.STRIPE_WEBHOOK_SECRET});return route.POST(new Request('https://example.test/api/commerce/webhook',{method:'POST',headers:{'stripe-signature':signature},body:payload}));}
test('signed paid event is amount-bound, idempotent and creates one confirmation outbox item',async()=>{const f=fixture();const {bookingId}=await f.commerce.createCheckout(user,input());const booking=f.db.data.get('commerceBookings/'+bookingId);const route=f.load(path.join(__dirname,'../src/app/api/commerce/webhook/route.ts'));const event={id:'evt_paid',type:'checkout.session.completed',livemode:false,data:{object:{id:booking.sessionId,metadata:{bookingId},amount_total:20000,currency:'eur',payment_status:'paid',payment_intent:'pi_test'}}};assert.equal((await eventRequest(route,event,true)).status,400);assert.equal((await eventRequest(route,{...event,data:{object:{...event.data.object,amount_total:1}}})).status,409);assert.equal((await eventRequest(route,event)).status,200);assert.equal((await eventRequest(route,event)).status,200);assert.equal(f.db.data.get('commerceBookings/'+bookingId).status,'paid');assert.equal([...f.db.data.keys()].filter(k=>k.startsWith('serviceOutbox/')).length,1);});
test('refund authorization and signed status confirmation are distinct',async()=>{const f=fixture();const {bookingId}=await f.commerce.createCheckout(user,input());const key='commerceBookings/'+bookingId;f.db.data.set(key,{...f.db.data.get(key),status:'paid',paymentIntent:'pi_test'});await assert.rejects(f.commerce.requestRefund(user,bookingId),e=>e.status===403);assert.equal(f.refundCount,0);f.db.data.set('adminAuth/operator',{role:'admin'});await f.commerce.requestRefund({...user,uid:'operator'},bookingId);assert.equal(f.db.data.get(key).status,'refund_pending');const route=f.load(path.join(__dirname,'../src/app/api/commerce/webhook/route.ts'));const event={id:'evt_refund',type:'refund.updated',livemode:false,data:{object:{id:'re_test_1',metadata:{bookingId},payment_intent:'pi_test',amount:20000,currency:'eur',status:'succeeded'}}};assert.equal((await eventRequest(route,event)).status,200);assert.equal(f.db.data.get(key).status,'refunded');});
test('expired checkout releases its slot and daily reservation; paid is not downgraded',async()=>{const f=fixture();const {bookingId}=await f.commerce.createCheckout(user,input());const key='commerceBookings/'+bookingId;const route=f.load(path.join(__dirname,'../src/app/api/commerce/webhook/route.ts'));const event={id:'evt_expired',type:'checkout.session.expired',livemode:false,data:{object:{id:f.db.data.get(key).sessionId,metadata:{bookingId}}}};assert.equal((await eventRequest(route,event)).status,200);assert.equal(f.db.data.get(key).status,'expired');assert.equal(f.db.data.get('commerceSlots/slot-1').available,true);assert.equal(f.db.data.get('commerceCalendar/real-mentor-test-2099-01-10').bookingId,null);});
test('disabled and unapproved live configuration fails closed',async()=>{const f=fixture();const old=process.env.SSB_COMMERCE_ENABLED;process.env.SSB_COMMERCE_ENABLED='false';await assert.rejects(f.commerce.createCheckout(user,input()),e=>e.status===503);process.env.SSB_COMMERCE_ENABLED=old;process.env.STRIPE_SECRET_KEY='sk_live_not_a_real_key';delete process.env.SSB_LIVE_PAYMENTS_APPROVED;assert.throws(()=>f.commerce.requireCommerce(),e=>e.status===503);process.env.STRIPE_SECRET_KEY='sk_test_not_a_real_key';});
test('Firebase identity rejects missing, revoked and unverified tokens',async()=>{
 process.env.FIREBASE_ADMIN_PROJECT_ID='unit-test';process.env.FIREBASE_ADMIN_CLIENT_EMAIL='server@example.test';process.env.FIREBASE_ADMIN_PRIVATE_KEY='not-a-real-key';let mode='valid';let checkedRevocation=false;
 const auth={verifyIdToken:async(token,revoked)=>{checkedRevocation=revoked;if(mode==='revoked')throw new Error('revoked');return{uid:'u',email:'a@example.test',email_verified:mode!=='unverified'};}};
 const load=loader({'firebase-admin/app':{getApps:()=>[{name:'ssb-server'}]},'firebase-admin/auth':{getAuth:()=>auth},'firebase-admin/firestore':{getFirestore:()=>({})}});const {identity}=load(path.join(__dirname,'../src/lib/server/admin.ts'));
 await assert.rejects(identity(new Request('https://example.test')),e=>e.status===401);
 const req=()=>new Request('https://example.test',{headers:{authorization:'Bearer dummy'}});
 mode='unverified';await assert.rejects(identity(req()),e=>e.status===403);mode='revoked';await assert.rejects(identity(req()),e=>e.status===401);mode='valid';assert.equal((await identity(req())).uid,'u');assert.equal(checkedRevocation,true);
});
test('newsletter confirmation requires valid unexpired token; unsubscribe cannot be reversed by replay',async()=>{
 const f=fixture();process.env.SSB_ENGAGEMENT_ENABLED='true';const token='a'.repeat(64),id='b'.repeat(64);f.db.data.set('newsletterSubscriptions/'+id,{status:'pending',tokenHash:crypto.createHash('sha256').update(token).digest('hex'),expiresAt:Date.now()+10000});const route=f.load(path.join(__dirname,'../src/app/api/engagement/confirm/route.ts'));
 const post=(action,secret=token)=>route.POST(new Request('https://example.test/api/engagement/confirm',{method:'POST',body:JSON.stringify({id,token:secret,action})}));
 assert.equal((await post('confirm','c'.repeat(64))).status,400);assert.equal(f.db.data.get('newsletterSubscriptions/'+id).status,'pending');assert.equal((await post('confirm')).status,200);assert.equal((await post('confirm')).status,200);assert.equal(f.db.data.get('newsletterSubscriptions/'+id).status,'subscribed');assert.equal((await post('unsubscribe')).status,200);assert.equal((await post('confirm')).status,400);assert.equal(f.db.data.get('newsletterSubscriptions/'+id).status,'unsubscribed');
});
test('booking messages are accessible only to traveler or privately linked mentor',async()=>{const f=fixture();const {bookingId}=await f.commerce.createCheckout(user,input());const {bookingAccess}=f.load(path.join(__dirname,'../src/lib/server/booking-access.ts'));assert.equal((await bookingAccess(user,bookingId)).role,'traveler');await assert.rejects(bookingAccess({...user,uid:'stranger'},bookingId),e=>e.status===403);f.db.data.set('mentorAuth/mentor-user',{mentorId:'real-mentor-test'});assert.equal((await bookingAccess({...user,uid:'mentor-user'},bookingId)).role,'mentor');});

test('configured card and PayPal reach Stripe; retry preserves the reserved configuration', async () => {
  const previous = process.env.SSB_STRIPE_PAYMENT_METHODS;
  try {
    process.env.SSB_STRIPE_PAYMENT_METHODS = 'card,paypal';
    const f = fixture(), i = input();
    const {bookingId} = await f.commerce.createCheckout(user, i);
    const key = 'commerceBookings/' + bookingId;
    assert.deepEqual(f.db.data.get(key).paymentMethods, ['card','paypal']);
    assert.deepEqual(f.sessions.get('checkout-' + bookingId).payment_method_types, ['card','paypal']);
    // Simulate a response lost before the session ID was saved, then a config change.
    const reserved = f.db.data.get(key); delete reserved.sessionId; reserved.status = 'creating';
    process.env.SSB_STRIPE_PAYMENT_METHODS = 'card';
    const original = structuredClone(f.sessions.get('checkout-' + bookingId));
    f.sessions.clear();
    await f.commerce.createCheckout(user, i);
    const retried = f.sessions.get('checkout-' + bookingId);
    assert.deepEqual(retried.payment_method_types, original.payment_method_types);
    assert.equal(retried.expires_at, original.expires_at);
    assert.deepEqual(retried.line_items, original.line_items);
    // Previously created bookings without a snapshot used card, even if PayPal is now configured.
    delete reserved.paymentMethods; delete reserved.sessionId; reserved.status = 'creating';
    f.db.data.set(key, reserved); f.sessions.clear();
    process.env.SSB_STRIPE_PAYMENT_METHODS = 'paypal';
    await f.commerce.createCheckout(user, i);
    assert.deepEqual(f.sessions.get('checkout-' + bookingId).payment_method_types, ['card']);
  } finally { if (previous === undefined) delete process.env.SSB_STRIPE_PAYMENT_METHODS; else process.env.SSB_STRIPE_PAYMENT_METHODS = previous; }
});
test('invalid payment configuration creates no reservation and client cannot override methods', async () => {
  const previous = process.env.SSB_STRIPE_PAYMENT_METHODS;
  try {
    process.env.SSB_STRIPE_PAYMENT_METHODS = 'card,sepa_debit';
    const f = fixture();
    await assert.rejects(f.commerce.createCheckout(user, input()), e => e.status === 503);
    assert.equal(f.createCount, 0);
    assert.equal(f.db.data.get('commerceSlots/slot-1').available, true);
    assert.equal([...f.db.data.keys()].filter(k => k.startsWith('commerceBookings/') || k.startsWith('commerceCalendar/')).length, 0);
    process.env.SSB_STRIPE_PAYMENT_METHODS = 'card';
    await assert.rejects(f.commerce.createCheckout(user, {...input(), paymentMethods: ['paypal']}), e => e.status === 400);
    assert.equal(f.createCount, 0);
  } finally { if (previous === undefined) delete process.env.SSB_STRIPE_PAYMENT_METHODS; else process.env.SSB_STRIPE_PAYMENT_METHODS = previous; }
});
