'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { useDemo } from './demo-provider';
import { demoPackages, money, today, tripError } from '@/lib/demo-booking';
import { originalMentors } from '@/components/content/original-mentors';
const box = 'rounded-3xl border bg-card p-5 sm:p-7';
const field = 'mt-2 block w-full rounded-xl border bg-background p-3 text-base';
export function DemoTrips() {
  const { state, dispatch } = useDemo(); const router = useRouter();
  return <section className={`${box} mb-8`}><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="text-xl">Meine Demo-Reisen</h2><p className="mt-2 text-sm text-muted-foreground">Hier findest du deine gespeicherten Reisen. Du kannst eine weitere Reise planen und jederzeit zurückwechseln.</p></div><Button disabled={!state.receipt || state.trips.length >= 10} onClick={() => { dispatch({ type: 'new-trip' }); router.push('/demo/pakete'); }}>Weitere Reise planen</Button></div>{state.trips.length >= 10 && <p className="mt-3 text-sm">Du hast die maximale Anzahl gespeicherter Reisen erreicht. Über „Neu beginnen“ kannst du alle Demo-Reisen löschen.</p>}<ul className="mt-5 grid gap-3 sm:grid-cols-2">{state.trips.map(t => <li key={t.receipt!.reference}><button className="w-full rounded-xl border p-4 text-left hover:border-primary" onClick={() => { dispatch({ type: 'open-trip', reference: t.receipt!.reference }); router.push('/demo/meine-reise'); }}><span className="block font-medium">{originalMentors.find(m => m.id === t.mentorId)!.city} · {demoPackages.find(p => p.id === t.packageId)!.name}</span><span className="mt-2 block text-xs">{t.trip.arrival} · {t.cancelled ? 'Storniert · Demo-Erstattung' : 'Bestätigt'} · {t.receipt!.reference}</span></button></li>)}</ul></section>;
}
export function DemoManagement() {
  const { state, dispatch } = useDemo(); const [trip, setTrip] = useState(state.trip); const [error, setError] = useState('');
  return <section className={`${box} my-6`}><h2 className="text-2xl">Änderungen & Benachrichtigungen</h2>{state.cancelled ? <p role="status" className="mt-5 rounded-xl bg-secondary p-5">Diese Demo-Reise ist storniert. Simulierte Erstattung: {money(state.refundAmount)}. Es wurde kein Geld bewegt. Die volle Erstattung ist ein Testszenario und keine reale Stornobedingung.</p> : <div className="mt-5 grid gap-5 md:grid-cols-2"><details className="rounded-xl border p-4"><summary className="cursor-pointer font-medium">Reisedaten ändern</summary><form className="mt-4" onSubmit={e => { e.preventDefault(); const issue = tripError(trip); setError(issue); if (!issue) dispatch({ type: 'change-trip', trip }); }}><label className="text-sm">Ankunft<input className={field} type="date" min={today()} required value={trip.arrival} onChange={e => setTrip({ ...trip, arrival: e.target.value })} /></label><label className="mt-4 block text-sm">Abreise<input className={field} type="date" required min={trip.arrival} value={trip.departure} onChange={e => setTrip({ ...trip, departure: e.target.value })} /></label><p className="mt-3 text-xs">Paket und Demo-Preis bleiben gleich. Bereits geplante Termine und Services werden zurückgesetzt.</p>{error && <p role="alert" className="mt-3 text-sm text-destructive">{error}</p>}<Button className="mt-4" type="submit">Änderung simulieren</Button></form></details><details className="rounded-xl border p-4"><summary className="cursor-pointer font-medium">Reise stornieren</summary><p className="mt-4 text-sm">Dieses Testszenario storniert die ausgewählte Reise und simuliert eine vollständige Erstattung. Andere Reisen bleiben erhalten.</p><Button className="mt-4" variant="destructive" onClick={() => dispatch({ type: 'cancel-trip' })}>Diese Demo-Reise stornieren</Button></details></div>}<h3 className="mt-6 text-lg">Dein Demo-Posteingang</h3><ol aria-live="polite" className="mt-4 space-y-2">{state.notifications.slice().reverse().map((n,i) => <li key={i} className="rounded-xl bg-muted/60 p-3 text-sm">{n}</li>)}</ol><p className="mt-4 text-xs text-muted-foreground">Lokale Hinweise innerhalb der Demo. Keine Push-Nachricht und keine E-Mail wird versendet.</p></section>;
}
export function DemoServices() {
  const { state, dispatch } = useDemo(); const [role, setRole] = useState<'traveler'|'mentor'>('traveler'); const [reply, setReply] = useState('');
  const [question, setQuestion] = useState(''); const [answer, setAnswer] = useState('');
  const features = demoPackages.find(p => p.id === state.packageId)!.features as readonly string[];
  const mentor = originalMentors.find(m => m.id === state.mentorId)!;
  const arrivalSteps = [['planned','Anreise geplant'],['landed','Gelandet'],['met','Treffpunkt erreicht'],['arrived','Ankunft abgeschlossen']];
  if (state.cancelled) return null;
  function ask() { const text = question.toLowerCase(); setAnswer(/flughafen|ankunft|airport/.test(text) ? 'Demo-Antwort: Halte deine Ankunftszeit und Unterkunft bereit. Im Ankunftsmodul kannst du das Treffen Schritt für Schritt simulieren.' : /tour|kultur|natur/.test(text) ? 'Demo-Antwort: Wähle im Premium-Paket eine Beispiel-Tour nach deinen Interessen. Die Vorschläge sind fiktiv und reservieren keine Aktivität.' : 'Demo-Antwort: Notiere deine Fragen für das Kennenlernen. Dein Reiseplan enthält Checkliste, Termine und die Leistungen deines Pakets. Für konkrete oder aktuelle Reiseauskünfte nutze verlässliche Originalquellen.'); }
  return <section className="my-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow mb-3">Deine Begleitung ausprobieren</p><h2 className="editorial-title section-title">Vor, während und nach der Ankunft.</h2></div><div className="flex flex-wrap gap-2"><Button variant={role === 'traveler' ? 'default' : 'outline'} aria-pressed={role === 'traveler'} onClick={() => setRole('traveler')}>Reisendenansicht</Button><Button variant={role === 'mentor' ? 'default' : 'outline'} aria-pressed={role === 'mentor'} onClick={() => setRole('mentor')}>Mentor-Gegenansicht</Button></div></div>
    {role === 'mentor' ? <div className={`${box} mt-6`}><p className="eyebrow">Lokales Rollenspiel · keine echte Anmeldung als Mentor</p><h3 className="mt-4 text-2xl">{mentor.name}: deine Demo-Begleitung</h3><p className="mt-4 text-sm">Anfrage von {state.trip.name} · {state.trip.arrival} bis {state.trip.departure}. Paket: {state.packageId}.</p><Button className="mt-4" disabled={state.services.mentorAccepted} onClick={() => dispatch({ type:'service',service:'mentorAccepted',value:true })}>{state.services.mentorAccepted ? 'Begleitung in der Demo bestätigt' : 'Begleitung als Mentor bestätigen'}</Button><h4 className="mt-6">Nachrichten der Reisenden</h4>{state.messages.length ? state.messages.map((m,i) => <p key={i} className="mt-2 rounded-xl bg-muted p-3 text-sm">{m}</p>) : <p className="mt-2 text-sm text-muted-foreground">Noch keine Demo-Nachricht eingegangen.</p>}<form className="mt-5" onSubmit={e => { e.preventDefault(); dispatch({ type:'mentor-reply',text:reply }); setReply(''); }}><label className="text-sm">Als Mentor antworten<textarea className={field} required maxLength={500} value={reply} onChange={e => setReply(e.target.value)} /></label><Button className="mt-3" disabled={!reply.trim() || state.mentorReplies.length >= 20}>Demo-Antwort speichern</Button></form></div> : <div className="mt-6 grid items-start gap-5 md:grid-cols-2">
      <section className={box}><h3 className="text-xl">KI Local Mentor</h3><p className="mt-3 text-sm text-muted-foreground">Offline-Simulation mit vorformulierten Antworten. Die Antworten werden nicht von einer KI erzeugt und enthalten keine aktuellen Sicherheitshinweise.</p><form onSubmit={e => { e.preventDefault(); ask(); }}><label className="mt-4 block text-sm">Deine Frage<textarea className={field} maxLength={500} required value={question} onChange={e => setQuestion(e.target.value)} placeholder="Wie kann ich meine Ankunft vorbereiten?" /></label><Button className="mt-3" disabled={!question.trim()}>Antwort simulieren</Button></form>{answer && <p role="status" className="mt-4 rounded-xl bg-secondary p-4 text-sm leading-relaxed">{answer}</p>}</section>
      <section className={box}><h3 className="text-xl">Reiseunterlagen</h3><p className="mt-3 text-sm leading-relaxed text-muted-foreground">Ein neu erstelltes Arbeitsheft mit Planungsfeldern, Packliste und Fragen für dein Kennenlernen. Das vollständige Original-Infopaket liegt weiterhin nicht vor.</p><Button asChild variant="outline" className="mt-5"><a href="/documents/reisebegleiter-de.pdf" download>Arbeitsheft als PDF</a></Button><Link className="mt-4 block text-sm underline" href="/reiseunterlagen">Unterlagen & Hinweise</Link></section>
      <section className={box}><h3 className="text-xl">Get-Ready-Call</h3>{features.includes('getready') ? <><p className="mt-3 text-sm">Fiktiver kurzer Check-in vor der Anreise. Es wird kein Videoraum geöffnet.</p><p className="mt-3 text-sm" role="status">Status: {state.services.ready === 'none' ? 'Noch nicht geplant' : state.services.ready === 'scheduled' ? 'In der Demo geplant' : 'Demo-Gespräch abgeschlossen'}</p><Button className="mt-4" disabled={state.services.ready === 'completed'} onClick={() => dispatch({ type:'service',service:'ready',value:state.services.ready === 'none' ? 'scheduled' : 'completed' })}>{state.services.ready === 'none' ? 'Demo-Call planen' : 'Demo-Call abschließen'}</Button></> : <p className="mt-3 text-sm text-muted-foreground">Im Premium-Paket enthalten. Für diesen Durchlauf nicht freigeschaltet.</p>}</section>
      <section className={box}><h3 className="text-xl">Ankunft am Flughafen</h3>{features.includes('ankunft') ? <><ol className="mt-4 space-y-2 text-sm">{arrivalSteps.map(([id,label],i) => <li key={id} className={arrivalSteps.findIndex(([id]) => id === state.services.arrival) >= i ? 'font-semibold' : 'text-muted-foreground'}>{i + 1}. {label}</li>)}</ol><p className="mt-4 text-xs text-muted-foreground">Fiktiver Ablauf ohne Flugverfolgung, Standortfreigabe oder echten Transfer.</p><Button className="mt-4" disabled={state.services.arrival === 'arrived'} onClick={() => dispatch({type:'service',service:'arrival',value:arrivalSteps[arrivalSteps.findIndex(([id]) => id === state.services.arrival)+1][0]})}>Nächsten Schritt simulieren</Button></> : <p className="mt-3 text-sm text-muted-foreground">Ab Standard enthalten. Für diesen Durchlauf nicht freigeschaltet.</p>}</section>
      <section className={box}><h3 className="text-xl">Deine Beispiel-Tour</h3>{features.includes('tour') ? <><p className="mt-3 text-sm">Wähle einen thematischen Entwurf. Es handelt sich nicht um eine verfügbare oder geprüfte Route.</p><div className="mt-4 flex flex-wrap gap-2">{[['culture','Kultur & Stadtgeschichten'],['nature','Natur & Ausblicke']].map(([id,label]) => <Button key={id} variant={state.services.tour === id ? 'default' : 'outline'} className="h-auto min-h-11 whitespace-normal" onClick={() => dispatch({type:'service',service:'tour',value:id})}>{label}</Button>)}</div>{state.services.tour !== 'none' && <div className="mt-4 rounded-xl bg-muted p-4 text-sm"><p>1. Gemeinsames Kennenlernen<br/>2. {state.services.tour === 'culture' ? 'Stadtgeschichten und persönliche Perspektiven' : 'Naturbeobachtung und Zeit für Fotos'}<br/>3. Pause und Ausklang</p><Button className="mt-4" disabled={state.services.tourDone} onClick={() => dispatch({type:'service',service:'tourDone',value:true})}>{state.services.tourDone ? 'Demo-Tour abgeschlossen' : 'Tourabschluss simulieren'}</Button></div>}</> : <p className="mt-3 text-sm text-muted-foreground">Im Premium-Paket enthalten. Für diesen Durchlauf nicht freigeschaltet.</p>}</section>
      <section className={box}><h3 className="text-xl">Antworten aus der Mentoransicht</h3><p className="mt-3 text-sm">{state.services.mentorAccepted ? 'Die Begleitung wurde im Rollenspiel bestätigt.' : 'Du kannst in der Mentor-Gegenansicht selbst auf deine Anfrage reagieren.'}</p><div role="log" aria-label="Simulierte Mentorantworten" aria-live="polite">{state.mentorReplies.map((r,i) => <p key={i} className="mt-3 rounded-xl bg-secondary p-4 text-sm">{r}</p>)}</div></section>
    </div>}
  </section>;
}
