'use client';
import {PaymentMethodPicker} from './payment-method-picker';
import {paymentMethodLabel} from '@/lib/payment-methods';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {useDemo} from './demo-provider';
import {demoPackages,tripError,today, type DemoTrip} from '@/lib/demo-booking';
import {originalMentors} from '@/components/content/original-mentors';
import {featureEnglish,citiesEnglish} from '@/lib/demo-english';
const card='rounded-3xl border bg-card p-6';const input='mt-2 block w-full rounded-xl border bg-background p-3';
const money=(n:number)=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'EUR'}).format(n/100);
export function DemoEnglish(){const {state,dispatch,ready,storageWarning}=useDemo();const [step,setStep]=useState(0);const [trip,setTrip]=useState<DemoTrip|null>(null);const [error,setError]=useState('');const [decline,setDecline]=useState(false);const [consent,setConsent]=useState(false);const [message,setMessage]=useState('');const [mentorRole,setMentorRole]=useState(false);const [ai,setAi]=useState('');const [answer,setAnswer]=useState('');
 if(!ready)return <p className="page-shell py-16">Preparing your demo …</p>;
 const draft=trip||{...state.trip,note:state.trip.note.startsWith('Ich reise')?'This is my first solo trip to South Africa. I would like to arrive at my own pace.':state.trip.note};
 const pkg=demoPackages.find(p=>p.id===state.packageId);const mentor=originalMentors.find(m=>m.id===state.mentorId)!;const features=(pkg?.features||[]) as readonly string[];
 const advance=()=>{if(!pkg){setError('Please choose a package.');return;}if(tripError(draft)){setError('Please enter a name and valid future dates, with departure after arrival and a stay of at most 28 days.');return;}dispatch({type:'cart',trip:draft});setStep(1);setError('');};
 return <div className="page-shell py-10" lang="en"><div className="mb-8 rounded-2xl bg-secondary p-5"><strong>Interactive demo.</strong> Fictional profiles and prices. No real payment, reservation, email or video call.<details className="mt-3 text-sm"><summary className="cursor-pointer underline">Start over</summary><Button variant="outline" className="mt-3" onClick={()=>{dispatch({type:'reset'});setStep(0);setTrip(null);setConsent(false);setError('');}}>Clear all demo journeys</Button></details></div>{storageWarning&&<p role="status">Browser storage is unavailable. Progress may be lost on reload.</p>}
 <h1 className="editorial-title page-title">Plan your trip to South Africa.</h1><p className="my-6 text-muted-foreground">Explore the complete booking experience as Anna, a solo traveller.</p>
 {state.trips.length>0&&<section className={`${card} my-6`}><h2 className="text-xl">Saved demo journeys</h2><div className="mt-4 flex flex-wrap gap-3">{state.trips.map(t=><Button key={t.receipt!.reference} variant="outline" onClick={()=>{dispatch({type:'open-trip',reference:t.receipt!.reference});setTrip(null);setStep(0);setMessage('');setMentorRole(false);setAnswer('');}}>{citiesEnglish[originalMentors.find(m=>m.id===t.mentorId)!.city]} · {t.trip.arrival}</Button>)}</div></section>}
 {!state.receipt?<>
 <nav aria-label="Booking steps" className="my-7 flex flex-wrap gap-3">{['Package & dates','Cart','Payment'].map((label,i)=><Button key={label} variant={step===i?'default':'outline'} disabled={i>0&&!state.inCart} onClick={()=>setStep(i)}>{i+1}. {label}</Button>)}</nav>
 {step===0&&<><label className="my-5 block text-sm">Your fictional local mentor<select className={input} value={state.mentorId} onChange={e=>dispatch({type:'choose',mentorId:e.target.value})}>{originalMentors.map(m=><option key={m.id} value={m.id}>{m.name} · {citiesEnglish[m.city]}</option>)}</select></label><div className="grid gap-5 lg:grid-cols-3">{demoPackages.map(p=><article key={p.id} className={card}><h2 className="text-2xl">{p.id==='basis'?'Basic':p.name}</h2><p className="my-4 text-3xl">{money(p.amount)}</p><p className="text-xs">Fictional total · one traveller</p><ul className="my-5 space-y-2 text-sm">{p.features.map(f=><li key={f}>✓ {featureEnglish[f]}</li>)}</ul><Button aria-pressed={state.packageId===p.id} variant={state.packageId===p.id?'default':'outline'} onClick={()=>dispatch({type:'choose',packageId:p.id})}>{state.packageId===p.id?'Selected':'Select package'}</Button></article>)}</div><form className={`${card} mt-6`} onSubmit={e=>{e.preventDefault();advance();}}><h2 className="text-xl">Your travel dates</h2><label className="mt-4 block text-sm">First name<input className={input} required maxLength={60} value={draft.name} onChange={e=>setTrip({...draft,name:e.target.value})}/></label><div className="mt-4 grid gap-4 sm:grid-cols-2"><label>Arrival<input className={input} type="date" required min={today()} value={draft.arrival} onChange={e=>setTrip({...draft,arrival:e.target.value})}/></label><label>Departure<input className={input} type="date" required min={draft.arrival} value={draft.departure} onChange={e=>setTrip({...draft,departure:e.target.value})}/></label></div><label className="mt-4 block text-sm">Your wishes<textarea className={input} maxLength={500} value={draft.note} onChange={e=>setTrip({...draft,note:e.target.value})}/></label><Button className="mt-5" disabled={!pkg}>Add to demo cart</Button></form></>}
 {step===1&&<section className={card}><h2 className="text-2xl">Your cart</h2>{state.inCart?<><p className="my-4">{pkg?.name} · {mentor.name} · {citiesEnglish[mentor.city]}</p><p>{state.trip.arrival} – {state.trip.departure}</p><p className="my-4 text-2xl">{money(pkg!.amount)}</p><p className="text-sm">Actually charged: €0.00</p><div className="mt-5 flex flex-wrap gap-3"><Button onClick={()=>setStep(2)}>Continue to demo payment</Button><Button variant="outline" onClick={()=>{dispatch({type:'remove'});setStep(0);}}>Remove package</Button></div></>:<><p className="my-5">Your cart is empty.</p><Button onClick={()=>setStep(0)}>Choose a package</Button></>}</section>}
 {step===2&&state.inCart&&<form className={card} onSubmit={e=>{e.preventDefault();if(!consent)return;if(tripError(state.trip)){setError('Please update your travel dates.');return;}dispatch({type:'payment',outcome:decline?'declined':'success',reference:`DEMO-${crypto.randomUUID().slice(0,13).toUpperCase()}`,createdAt:new Date().toISOString()});if(decline)setError('Demo payment declined. Your selection has been kept; switch to success and retry.');else setError('');}}><h2 className="text-2xl">Simulate a payment</h2><p className="my-4">No card or bank details required.</p><PaymentMethodPicker language="en" value={state.paymentMethod} onChange={method=>{dispatch({type:'payment-method',method});setConsent(false);setError('');}}/><label className="block text-sm">Test outcome<select className={input} value={decline?'declined':'success'} onChange={e=>setDecline(e.target.value==='declined')}><option value="success">Payment successful</option><option value="declined">Payment declined</option></select></label><label className="my-5 flex items-start gap-3 text-sm"><input type="checkbox" required checked={consent} onChange={e=>setConsent(e.target.checked)}/>I understand that this is a fictional booking with no costs or entitlement to services.</label><div className="flex flex-wrap gap-3"><Button className="h-auto min-h-12 whitespace-normal" disabled={!consent}>Simulate {paymentMethodLabel(state.paymentMethod,'en')}</Button><Button type="button" variant="outline" onClick={()=>{dispatch({type:'payment',outcome:'cancelled',reference:'',createdAt:''});setStep(1);setError('Payment cancelled. Your cart has been kept.');}}>Cancel payment</Button></div></form>}
 </>:<>
 <section className={`${card} my-6`}><p className="eyebrow">{state.cancelled?'Demo booking cancelled':'Demo booking confirmed'}</p><h2 className="mt-4 text-2xl">{draft.name}, your journey to {citiesEnglish[mentor.city]}</h2><p className="mt-4">{pkg?.name} · {mentor.name} · {money(state.receipt.amount)}</p><p className="mt-3 text-sm">Simulated payment method: {paymentMethodLabel(state.receipt.paymentMethod,'en')}</p><p className="mt-3 font-mono text-xs">{state.receipt.reference}</p><p className="mt-4 text-sm">Demo inbox: {state.cancelled?'A full refund has been simulated. No money was transferred. This is not a real cancellation policy.':'Your selection has been confirmed in this browser. No email was sent.'}</p><Button className="mt-5" disabled={state.trips.length>=10} onClick={()=>{dispatch({type:'new-trip'});setStep(0);setTrip(null);setError('');setMessage('');setMentorRole(false);setAnswer('');}}>Plan another journey</Button></section>
 {!state.cancelled&&<><div className="my-6 grid gap-5 md:grid-cols-2"><section className={card}><h2 className="text-xl">Your travel checklist</h2>{['Check travel dates','Prepare questions for the introductory call','Plan accommodation and arrival','Prepare a personal packing list'].map((text,i)=><label key={text} className="mt-4 flex gap-3 text-sm"><input type="checkbox" checked={state.checklist.includes(i)} onChange={()=>dispatch({type:'check',index:i})}/>{text}</label>)}<a className="mt-5 block text-sm underline" href="/documents/reisebegleiter-en.pdf" download>Download your new travel workbook (PDF)</a><p className="mt-2 text-xs text-muted-foreground">A planning workbook for your dates, arrival details and questions. It does not contain current travel advice.</p></section><section className={card}><h2 className="text-xl">Introductory call</h2><p className="my-4 text-sm">Fictional time in South Africa (UTC+2). No invitation or video room is created.</p>{['10:00','14:00','17:00'].map(time=><Button key={time} className="mr-2 mb-2" variant={state.appointment===time?'default':'outline'} onClick={()=>dispatch({type:'appointment',time:time as '10:00'|'14:00'|'17:00'})}>{time}</Button>)}</section>
 <section className={card}><h2 className="text-xl">AI mentor simulation</h2><p className="my-4 text-sm">Offline, predefined responses. No generative model or current travel advice.</p><label className="text-sm">Your question<input value={ai} maxLength={500} className={input} onChange={e=>setAi(e.target.value)}/></label><Button className="mt-4" disabled={!ai.trim()} onClick={()=>setAnswer(/arrival|airport/i.test(ai)?'Prepare your arrival details and accommodation address. You can try the airport arrival module in Standard or Premium.':/tour|nature|culture/i.test(ai)?'In Premium, choose a fictional tour theme below. No real activity is reserved.':'Write down your questions and agree on the details during your introductory call. The checklist can help you prepare.')}>Simulate reply</Button><p role="status" className="mt-4 text-sm">{answer}</p></section>
 <section className={card}><h2 className="text-xl">Get-ready call · Premium</h2>{features.includes('getready')?<><p className="my-4 text-sm">Status: {state.services.ready}</p><Button disabled={state.services.ready==='completed'} onClick={()=>dispatch({type:'service',service:'ready',value:state.services.ready==='none'?'scheduled':'completed'})}>{state.services.ready==='none'?'Schedule demo call':'Complete demo call'}</Button></>:<p className="mt-4 text-sm">Not included in this package.</p>}</section>
 <section className={card}><h2 className="text-xl">Airport arrival · Standard / Premium</h2>{features.includes('ankunft')?<><p className="my-4 text-sm">Planned → Landed → Meeting point → Arrived</p><p className="mb-4 text-sm">Current step: {state.services.arrival}</p><Button disabled={state.services.arrival==='arrived'} onClick={()=>dispatch({type:'service',service:'arrival',value:['planned','landed','met','arrived'][['planned','landed','met','arrived'].indexOf(state.services.arrival)+1]})}>Simulate next step</Button></>:<p className="mt-4 text-sm">Not included in this package.</p>}</section>
 <section className={card}><h2 className="text-xl">Tour · Premium</h2>{features.includes('tour')?<><p className="my-4 text-sm">Fictional themes, no verified route or real activity.</p>{(['culture','nature'] as const).map(theme=><Button key={theme} variant={state.services.tour===theme?'default':'outline'} className="mr-3 mb-3" onClick={()=>dispatch({type:'service',service:'tour',value:theme})}>{theme==='culture'?'Culture & stories':'Nature & views'}</Button>)}<Button disabled={state.services.tour==='none'||state.services.tourDone} onClick={()=>dispatch({type:'service',service:'tourDone',value:true})}>{state.services.tourDone?'Demo tour completed':'Complete demo tour'}</Button></>:<p className="mt-4 text-sm">Not included in this package.</p>}</section></div>
 <section className={`${card} my-6`}><h2 className="text-2xl">Two sides of the conversation</h2><p className="my-4 text-sm">Role-play in this browser. No real mentor receives messages.</p><Button variant="outline" onClick={()=>setMentorRole(!mentorRole)}>{mentorRole?'Switch to traveller view':'Switch to mentor view'}</Button>{mentorRole&&<Button className="ml-2" disabled={state.services.mentorAccepted} onClick={()=>dispatch({type:'service',service:'mentorAccepted',value:true})}>{state.services.mentorAccepted?'Support accepted in demo':'Accept demo support'}</Button>}<div className="my-4 max-h-60 space-y-2 overflow-y-auto" role="log">{state.messages.map((m,i)=><p key={`t${i}`} className="rounded-xl bg-muted p-3 text-sm">Traveller: {m}</p>)}{state.mentorReplies.map((m,i)=><p key={`m${i}`} className="rounded-xl bg-secondary p-3 text-sm">Mentor role-play: {m}</p>)}</div><form onSubmit={e=>{e.preventDefault();dispatch({type:mentorRole?'mentor-reply':'message',text:message});setMessage('');}}><label className="text-sm">{mentorRole?'Your mentor reply':'Your traveller message'}<textarea value={message} maxLength={500} className={input} onChange={e=>setMessage(e.target.value)}/></label><Button className="mt-3" disabled={!message.trim()||(mentorRole?state.mentorReplies.length:state.messages.length)>=20}>Save demo message</Button></form></section>
 <section className={card}><h2 className="text-xl">Change or cancel your journey</h2><details className="mt-4"><summary className="cursor-pointer">Change dates</summary><form onSubmit={e=>{e.preventDefault();if(tripError(draft)){setError('Check your future dates and keep the stay within 28 days.');return;}dispatch({type:'change-trip',trip:draft});setError('Dates updated. Please re-plan your appointments and services.');}}><label className="mt-4 block">Arrival<input className={input} type="date" required min={today()} value={draft.arrival} onChange={e=>setTrip({...draft,arrival:e.target.value})}/></label><label className="mt-4 block">Departure<input className={input} type="date" required min={draft.arrival} value={draft.departure} onChange={e=>setTrip({...draft,departure:e.target.value})}/></label><Button className="mt-4">Save demo change</Button></form></details><details className="mt-5"><summary className="cursor-pointer">Cancel journey</summary><p className="my-4 text-sm">This test simulates a full refund. It is not a real refund policy.</p><Button variant="destructive" onClick={()=>dispatch({type:'cancel-trip'})}>Cancel this demo journey</Button></details></section>
 </>}
 </>}
 <p role="status" className="my-6 text-sm">{error}</p><p className="mt-8 border-t pt-5 text-xs text-muted-foreground">Progress is stored locally in your browser. Use example data only.</p></div>;
}
