'use client';
import {useEffect,useState} from 'react';
import {useUser} from '@/firebase';
import {Button} from '@/components/ui/button';
export default function Operations(){const {user}=useUser();const [data,setData]=useState<{applications:any[];bookings:any[];outbox:any[]}>({applications:[],bookings:[],outbox:[]});const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);
 async function load(){if(!user)return;try{const r=await fetch('/api/operations',{headers:{Authorization:`Bearer ${await user.getIdToken()}`}});const d=await r.json();if(r.ok)setData(d);else setNotice(d.error);}catch{setNotice('Verbindung fehlgeschlagen.');}}
 useEffect(()=>{void load();},[user]);
 async function action(body:Record<string,unknown>,url='/api/operations'){if(!user||busy)return;setBusy(true);try{const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${await user.getIdToken()}`},body:JSON.stringify(body)});const d=await r.json();setNotice(d.message||d.error||d.status);await load();}catch{setNotice('Anfrage fehlgeschlagen. Status vor Wiederholung prüfen.');}finally{setBusy(false);}}
 return <div className="py-8"><h1 className="text-3xl">Betrieb & Freigaben</h1><p className="my-4 text-sm">Bewerbung, Profilprüfung und Angebotsfreigabe sind getrennte Schritte. Änderungen hier sind echte Server-Aktionen.</p><Button variant="outline" onClick={load}>Aktualisieren</Button><p role="status" className="my-4">{notice}</p><h2 className="mt-8 text-xl">Bewerbungen</h2>{data.applications.map(a=><article key={a.id} className="my-4 rounded-2xl border p-5"><h3>{a.name} · {a.city}</h3><p className="mt-2 text-sm">{a.email} · {a.languages} · {a.status}</p><p className="my-4 text-sm">{a.message}</p><div className="flex flex-wrap gap-3">{[['reviewing','In Prüfung'],['approved','Bewerbung freigeben'],['rejected','Ablehnen']].map(([status,label])=><Button key={status} variant="outline" disabled={busy} onClick={()=>action({action:'application',id:a.id,status})}>{label}</Button>)}</div></article>)}<h2 className="mt-8 text-xl">Buchungen & Kundenwünsche</h2>{data.bookings.map(b=><article key={b.id} className="my-4 rounded-2xl border p-5"><h3>{b.offer.title} · {b.status}</h3><p className="mt-2 text-sm">{b.arrival} – {b.departure} · {b.email}</p>{b.customerRequest&&<p className="mt-3 text-sm">{b.customerRequest.action}: {b.customerRequest.message}</p>}{b.status==='paid'&&<details className="mt-4"><summary className="cursor-pointer">Vollständige Erstattung</summary><p className="my-3 text-sm">Nur nach Prüfung der vereinbarten Stornobedingungen. Diese Aktion beauftragt eine echte Erstattung in der konfigurierten Stripe-Umgebung.</p><Button variant="destructive" disabled={busy} onClick={()=>action({bookingId:b.id,confirmFullRefund:true},'/api/commerce/refund')}>Vollständige Erstattung verbindlich beauftragen</Button></details>}</article>)}<h2 className="mt-8 text-xl">E-Mail-Ausgang</h2><p className="my-3 text-sm">„accepted“ bedeutet vom Versanddienst angenommen, nicht nachweislich im Postfach zugestellt. Nach mehr als 23 Stunden seit einem unklaren Versandversuch ist eine manuelle Prüfung erforderlich.</p>{data.outbox.map(o=><div key={o.id} className="my-3 rounded-xl border p-4"><p className="text-sm">{o.subject} · {o.status}</p>{o.status!=='accepted'&&<Button variant="outline" className="mt-3" disabled={busy} onClick={()=>action({action:'retry-mail',id:o.id})}>Versand erneut versuchen</Button>}</div>)}</div>;
}
