import Link from 'next/link';
import {notFound} from 'next/navigation';
import {originalMentors} from '@/components/content/original-mentors';
import {originalAssets} from '@/components/content/original-assets';
import {OriginalTeamPortrait} from '@/components/content/original-team-portrait';
import {EngagementForm} from '@/components/product/engagement-form';
import {Button} from '@/components/ui/button';
import {citiesEnglish,featureEnglish} from '@/lib/demo-english';
import {demoPackages} from '@/lib/demo-booking';
const sections=['mentors','about','stories','documents','join','faq','packages'];
export const dynamicParams=false;
export function generateStaticParams(){return sections.map(section=>({section}));}
export async function generateMetadata({params}:{params:Promise<{section:string}>}){const {section}=await params;return {title:`${section.charAt(0).toUpperCase()+section.slice(1)} · Stay Safe & Brave`,alternates:{languages:{en:`/en/${section}`}}};}
export default async function Page({params}:{params:Promise<{section:string}>}){const {section}=await params;if(!sections.includes(section))notFound();const title={mentors:'Local perspectives. Personal connections.',about:'The people behind the idea.',stories:'A little inspiration for your journey.',documents:'Make room for your plans.',join:'Your perspective matters.',faq:'Clarity before your next adventure.',packages:'Support that fits your journey.'}[section];return <div lang="en" className="page-shell py-12"><p className="eyebrow mb-4">Stay Safe & Brave</p><h1 className="editorial-title page-title">{title}</h1>
 {section==='mentors'&&<><p className="my-6 text-muted-foreground">These nine profiles are fictional examples, not verified or available mentors. They can be used in the booking simulation.</p><div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{originalMentors.map(m=><article key={m.id} className="overflow-hidden rounded-3xl border bg-card"><img src={m.image} alt={`Fictional example profile: ${m.name}`} width={400} height={400} className="aspect-square w-full object-cover object-top"/><div className="p-5"><p className="text-xs text-primary">FICTIONAL EXAMPLE</p><h2 className="mt-2 text-xl">{m.name}</h2><p className="mt-2 text-sm">{citiesEnglish[m.city]} · age {m.age} in this example</p><Button asChild className="mt-4"><Link href="/en/demo">Choose a profile in the demo</Link></Button><Link className="mt-4 block text-xs underline" href={`/mentors/profil/${m.id}`}>Read the detailed German profile</Link></div></article>)}</div></>}
 {section==='about'&&<><p className="my-7 max-w-3xl text-lg leading-relaxed text-muted-foreground">Stay Safe & Brave connects independent travellers with local perspectives in South Africa. You organise your own journey; the personal support and its scope are agreed separately. The platform is still being developed.</p><div className="grid gap-8 md:grid-cols-3">{(['Laura','Niklas','Houssam'] as const).map((name,i)=><article className="border-t pt-5" key={name}><OriginalTeamPortrait name={name}/><h2 className="text-2xl">{name}</h2><p className="mt-3">{['CEO & Visionary','COO & CMO','CTO'][i]}</p><p className="mt-3 text-sm text-muted-foreground">{['Strategy, vision and social impact','Business development, sales and marketing','Technology and innovation'][i]}</p></article>)}</div></>}
 {section==='stories'&&<><p className="my-6 max-w-2xl text-muted-foreground">A selection from the original brand archive. These photographs are not presented as new community reports or bookable tours.</p><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{[[originalAssets.boKaap,'Bo-Kaap'],[originalAssets.clifton,'Clifton'],[originalAssets.boulders,'Boulders Beach']].map(([src,label])=><figure key={src} className="overflow-hidden rounded-3xl border"><img src={src} alt={label} className="aspect-[4/3] w-full object-cover"/><figcaption className="p-5">{label} · brand archive</figcaption></figure>)}</div><p className="mt-7 text-sm">Community reports are not automatically translated. <Link href="/stories" className="underline">Open the German community section</Link>.</p></>}
 {section==='documents'&&<div className="my-8 max-w-2xl rounded-3xl border bg-card p-7"><h2 className="text-2xl">Your four-page travel workbook</h2><p className="my-5 text-sm leading-relaxed">Planning fields, questions for your introductory meeting, arrival details, a personal packing list and notes. Newly created for this project; the complete historical information pack has not been provided. No current visa, medical or safety advice is included.</p><Button asChild><a href="/documents/reisebegleiter-en.pdf" download>Download English PDF</a></Button></div>}
 {section==='join'&&<div className="mt-8 grid items-start gap-6 lg:grid-cols-2"><EngagementForm kind="mentor" en/><EngagementForm kind="newsletter" en/></div>}
 {section==='packages'&&<><p className="my-6 text-muted-foreground">Fictional demo prices. No payment or real booking is made.</p><div className="grid gap-5 lg:grid-cols-3">{demoPackages.map(p=><article key={p.id} className="rounded-3xl border bg-card p-6"><h2 className="text-2xl">{p.id==='basis'?'Basic':p.name}</h2><p className="my-5 text-3xl">€{p.amount/100}</p><ul className="space-y-3 text-sm">{p.features.map(f=><li key={f}>✓ {featureEnglish[f]}</li>)}</ul></article>)}</div><Button asChild className="mt-7"><Link href="/en/demo">Start the demo</Link></Button></>}
 {section==='faq'&&<div className="my-8 max-w-3xl">{[['Does the demo charge money?','No. All demo prices, bookings, payments, refunds, messages and appointments are simulated locally. No payment or bank details are requested.'],['Are the example mentors verified?','No. The nine example profiles are fictional. A real offer must be separately reviewed, approved and connected to confirmed availability before it can be sold.'],['Can I try the mentor role?','Yes. After a successful demo payment, switch to the mentor view to accept the fictional request and reply to the traveller.'],['How do I keep several trips?','Choose Plan another journey after confirmation. Existing trips remain in the same browser. Start over clears all local demo data.'],['Is the entire platform available in English?','The public English introduction, packages, workbook, participation forms and booking demo are available. Detailed legacy profiles, community content, real booking operations, account areas and legal pages remain in German.'],['How does a real newsletter subscription work?','A request alone does not subscribe you. You must open the confirmation link and explicitly confirm. Demo forms simulate these steps without sending email.']].map(([q,a])=><details key={q} className="border-b py-5"><summary className="cursor-pointer font-medium">{q}</summary><p className="mt-4 text-sm leading-relaxed text-muted-foreground">{a}</p></details>)}</div>}
 </div>;}
