'use client';
import {useState} from 'react';
import {useUser} from '@/firebase';
import {Button} from '@/components/ui/button';
export function BookingConversation({bookingId}:{bookingId:string}){const {user}=useUser();const [messages,setMessages]=useState<{id:string;text:string;role:string}[]>([]);const [appointment,setAppointment]=useState<{date:string;status:string;proposedBy:string}|null>(null);const [text,setText]=useState('');const [date,setDate]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);
 async function load(){if(!user)return;try{const r=await fetch(`/api/commerce/conversation?bookingId=${encodeURIComponent(bookingId)}`,{headers:{Authorization:`Bearer ${await user.getIdToken()}`}});const d=await r.json();if(!r.ok)throw new Error(d.error);setMessages(d.messages);setAppointment(d.appointment);}catch(e){setNotice(e instanceof Error?e.message:'Laden fehlgeschlagen.');}}
 async function submit(action:string){if(!user||busy)return;setBusy(true);try{const r=await fetch('/api/commerce/conversation',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${await user.getIdToken()}`},body:JSON.stringify({bookingId,action,text,...(action==='propose'?{date:new Date(date).toISOString()}:{}),requestId:crypto.randomUUID()})});const d=await r.json();setNotice(d.message||d.error);if(r.ok){setText('');await load();}}catch{setNotice('Verbindung fehlgeschlagen. Bitte Status prüfen, bevor du erneut sendest.');}finally{setBusy(false);}}
 return <details className="mt-6 border-t pt-5" onToggle={e=>{if(e.currentTarget.open)void load();}}><summary className="cursor-pointer font-medium">Nachrichten & Kennenlerntermin</summary><Button variant="ghost" className="my-3" onClick={load}>Aktualisieren</Button><div role="log" className="max-h-72 space-y-3 overflow-y-auto">{messages.map(m=><p key={m.id} className="rounded-xl bg-muted p-3 text-sm"><strong>{m.role==='mentor'?'Mentor':'Reisende'}: </strong>{m.text}</p>)}</div><label className="mt-4 block text-sm">Nachricht<textarea value={text} maxLength={2000} onChange={e=>setText(e.target.value)} className="mt-2 w-full rounded-xl border bg-background p-3"/></label><Button disabled={busy||!text.trim()} onClick={()=>submit('message')}>Nachricht senden</Button><label className="mt-5 block text-sm">Terminvorschlag (deine lokale Uhrzeit)<input type="datetime-local" value={date} onChange={e=>setDate(e.target.value)} className="my-2 block w-full rounded-xl border bg-background p-3"/></label><Button variant="outline" disabled={busy||!date||Date.parse(date)<Date.now()} onClick={()=>submit('propose')}>Termin vorschlagen</Button>{appointment&&<p className="mt-4 text-sm">{new Date(appointment.date).toLocaleString()} · {appointment.status==='confirmed'?'Bestätigt':'Vorgeschlagen'} {appointment.status==='proposed'&&appointment.proposedBy!==user?.uid&&<Button variant="outline" disabled={busy} onClick={()=>submit('confirm')}>Termin bestätigen</Button>}</p>}<p role="status" className="mt-4 text-sm">{notice}</p></details>;
}
