'use client';
import { useEffect,useState } from 'react';
import Link from 'next/link';
import { useUser } from '@/firebase';
import { Button } from '@/components/ui/button';
import type { Offer,CommerceBooking } from '@/lib/commerce/model';
import { paymentMethodLabel, type CheckoutPaymentMethod } from '@/lib/payment-methods';
import { money } from '@/lib/demo-booking';
import { BookingConversation } from './booking-conversation';
type PublicOffer=Offer&{id:string;slots:{id:string;arrival:string;departure:string}[]};
export function CommercePanel(){const {user}=useUser();const [paymentMethods,setPaymentMethods]=useState<CheckoutPaymentMethod[]>([]);const [offers,setOffers]=useState<PublicOffer[]>([]);const [bookings,setBookings]=useState<(CommerceBooking&{id:string})[]>([]);const [notice,setNotice]=useState('Angebote werden geladen …');const [busy,setBusy]=useState(false);const [request,setRequest]=useState<Record<string,string>>({});
 async function load(){try{const r=await fetch('/api/commerce/offers');const d=await r.json();if(!r.ok)throw new Error(d.error);setOffers(d.offers);setPaymentMethods(d.paymentMethods||['card']);setNotice(d.enabled?(d.offers.length?'':'Noch keine geprüften Angebote veröffentlicht.'):'Echte Buchungen sind noch nicht freigeschaltet. Die interaktive Demo steht bereit.');if(user){const b=await fetch('/api/commerce/bookings',{headers:{Authorization:`Bearer ${await user.getIdToken()}`}});const data=await b.json();if(!b.ok)throw new Error(data.error);setBookings(data.bookings);}}catch(e){setNotice(e instanceof Error?e.message:'Verbindung fehlgeschlagen.');}}
 useEffect(()=>{void load();},[user]);
 return <><p role="status" className="my-6 text-sm">{notice}</p><div className="flex flex-wrap gap-3"><Button asChild><Link href="/demo">Demo ausprobieren</Link></Button><Button variant="outline" onClick={load}>Status aktualisieren</Button>{!user&&<Button asChild variant="outline"><Link href="/auth/login">Für echte Anfragen anmelden</Link></Button>}</div>{offers.length>0&&<p className="mt-6 rounded-2xl bg-secondary/50 p-4 text-sm leading-relaxed">Wähle deine Zahlungsmethode anschließend im Stripe-Checkout: {paymentMethods.map(method=>paymentMethodLabel(method)).join(', ')}.{paymentMethods.includes('card')&&<span className="mt-1 block text-xs text-muted-foreground">Apple Pay und Google Pay werden dort angeboten, wenn Gerät, Wallet und Einrichtung dies unterstützen.</span>}</p>}<div className="mt-8 grid gap-5 lg:grid-cols-2">{offers.map(o=><form key={o.id} className="rounded-3xl border bg-card p-6" onSubmit={async e=>{e.preventDefault();if(!user||busy)return;const data=new FormData(e.currentTarget);setBusy(true);try{const key=`${o.id}:${data.get('slot')}`;const requestId=request[key]||crypto.randomUUID();setRequest(prev=>({...prev,[key]:requestId}));const r=await fetch('/api/commerce/checkout',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${await user.getIdToken()}`},body:JSON.stringify({offerId:o.id,slotId:data.get('slot'),requestId,acceptedTermsVersion:o.termsVersion})});const result=await r.json();if(!r.ok)throw new Error(result.error);const url=new URL(result.url);if(url.protocol!=='https:'||url.hostname!=='checkout.stripe.com')throw new Error('Unbekannte Zahlungsadresse.');window.location.assign(url.href);}catch(e){setNotice(e instanceof Error?e.message:'Checkout fehlgeschlagen.');}finally{setBusy(false);}}}><h2 className="text-2xl">{o.title}</h2><p className="mt-2 text-sm">{o.mentorName} · {o.city}</p><p className="mt-4 text-3xl">{money(o.amount)}</p><ul className="mt-4 list-inside list-disc text-sm">{o.features.map(f=><li key={f}>{f}</li>)}</ul><label className="mt-5 block text-sm">Bestätigter Zeitraum<select name="slot" required className="mt-2 w-full rounded-xl border bg-background p-3"><option value="">Zeitraum wählen</option>{o.slots.map(s=><option key={s.id} value={s.id}>{s.arrival} bis {s.departure}</option>)}</select></label><details className="my-4"><summary className="cursor-pointer">Leistungs- und Stornobedingungen</summary><p className="mt-3 whitespace-pre-wrap text-sm">{o.terms}</p></details><label className="flex items-start gap-3 text-sm"><input className="mt-1" type="checkbox" required/>Ich akzeptiere diese Leistungsbedingungen ({o.termsVersion}).</label><Button className="mt-5" disabled={!user||busy||!o.slots.length}>Zur sicheren Zahlung</Button></form>)}</div>
 {user&&<section className="mt-12"><h2 className="editorial-title section-title">Meine Buchungen</h2><p className="my-4 text-sm text-muted-foreground">Der Status kommt vom Server. Eine Weiterleitung zurück zur Website bestätigt keine Zahlung.</p>{bookings.length===0&&<p className="text-sm">Noch keine Buchungen vorhanden.</p>}{bookings.map(b=><article key={b.id} className="my-5 rounded-3xl border bg-card p-6"><h3 className="text-xl">{b.offer.title}</h3><p className="mt-3 text-sm">{b.arrival} – {b.departure} · {money(b.offer.amount)}</p><p className="mt-3 text-sm">Status: {{creating:'Zahlung wird vorbereitet',checkout:'Zahlung noch nicht bestätigt',paid:'Zahlung bestätigt',expired:'Zahlungssitzung abgelaufen',refund_pending:'Erstattung wird verarbeitet',refunded:'Erstattung bestätigt',refund_failed:'Erstattung fehlgeschlagen – Teamprüfung erforderlich'}[b.status]}</p><p className="mt-2 break-all font-mono text-xs">{b.id}</p>{['creating','checkout'].includes(b.status)&&b.requestId&&<Button variant="outline" className="mt-4" disabled={busy} onClick={async()=>{setBusy(true);try{const r=await fetch('/api/commerce/checkout',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${await user.getIdToken()}`},body:JSON.stringify({offerId:b.offerId,slotId:b.slotId,requestId:b.requestId,acceptedTermsVersion:b.offer.termsVersion})});const d=await r.json();if(!r.ok)throw new Error(d.error);const u=new URL(d.url);if(u.protocol!=='https:'||u.hostname!=='checkout.stripe.com')throw new Error('Unbekannte Zahlungsadresse.');window.location.assign(u.href);}catch(e){setNotice(e instanceof Error?e.message:'Fortsetzen fehlgeschlagen.');}finally{setBusy(false);}}}>Zahlung fortsetzen</Button>}{b.status==='paid'&&<><form className="mt-4" onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy(true);const d=new FormData(e.currentTarget);try{const r=await fetch('/api/commerce/bookings',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${await user.getIdToken()}`},body:JSON.stringify({bookingId:b.id,action:d.get('action'),message:d.get('message')})});const data=await r.json();setNotice(data.message||data.error);}catch{setNotice('Verbindung fehlgeschlagen.');}finally{setBusy(false);}}}><label className="block text-sm">Dein Wunsch<select name="action" className="my-2 block w-full rounded-xl border bg-background p-3"><option value="change-request">Änderung anfragen</option><option value="cancel-request">Storno anfragen</option></select></label><label className="text-sm">Details<textarea name="message" required minLength={5} maxLength={1000} className="mt-2 block w-full rounded-xl border bg-background p-3"/></label><Button variant="outline" className="mt-3" disabled={busy}>Anfrage speichern</Button></form><BookingConversation bookingId={b.id}/></>}</article>)}</section>}</>;
}
