'use client';
import { useCallback, useState } from 'react';
import { Button } from '@/components/ui/button';
import { Turnstile } from './turnstile';
const field='mt-2 block w-full rounded-xl border bg-background p-3';
export function EngagementForm({kind,en=false}:{kind:'mentor'|'newsletter';en?:boolean}){
 const [demo,setDemo]=useState(true);const [token,setToken]=useState('');const callback=useCallback((t:string)=>setToken(t),[]);const [attempt,setAttempt]=useState(0);const [busy,setBusy]=useState(false);const [notice,setNotice]=useState('');const [stage,setStage]=useState('form');
 const t=(de:string,english:string)=>en?english:de;
 return <section className="rounded-3xl border bg-card p-6 sm:p-8"><h2 className="text-2xl">{kind==='mentor'?t('Local Mentor werden','Become a local mentor'):t('In Verbindung bleiben','Stay in touch')}</h2><p className="mt-3 text-sm text-muted-foreground">{kind==='mentor'?t('Erzähle uns von dir. Eine Bewerbung ist noch keine Freigabe als Mentor.','Tell us about yourself. An application does not grant mentor status.'):t('Reiseideen und Neuigkeiten. Eine echte Anmeldung erfordert die Bestätigung per E-Mail.','Travel ideas and updates. A real subscription requires email confirmation.')}</p><label className="my-5 flex items-center gap-3 text-sm"><input type="checkbox" checked={demo} onChange={e=>{setDemo(e.target.checked);setNotice('');setStage('form');setToken('');}}/>{t('Nur als Demo ausprobieren (kein Versand)','Try as a demo only (nothing is sent)')}</label>
 {stage==='form'?<form onSubmit={async e=>{e.preventDefault();if(busy)return;const form=new FormData(e.currentTarget);if(demo){setStage('pending');setNotice('');return;}setBusy(true);setNotice('');try{const response=await fetch('/api/engagement',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind,email:form.get('email'),name:form.get('name')||'',city:form.get('city')||'',languages:form.get('languages')||'',message:form.get('message')||'',website:form.get('website')||'',consent:form.get('consent')==='on',token})});const data=await response.json();setNotice(data.message||data.error);if(response.ok)setStage('submitted');}catch{setNotice(t('Verbindung fehlgeschlagen. Bitte erneut versuchen.','Connection failed. Please try again.'));}finally{setBusy(false);setToken('');setAttempt(n=>n+1);}}}>
 <label className="block text-sm">{t('E-Mail-Adresse','Email address')}<input className={field} name="email" type="email" required maxLength={254} placeholder={demo?'anna@example.test':undefined}/></label>
 {kind==='mentor'&&<>{[['name',t('Name','Name')],['city',t('Stadt / Region','City / region')],['languages',t('Sprachen','Languages')]].map(([name,label])=><label key={name} className="mt-4 block text-sm">{label}<input className={field} name={name} required minLength={2} maxLength={100}/></label>)}<label className="mt-4 block text-sm">{t('Vorstellung & Motivation','Introduction and motivation')}<textarea className={field} name="message" required minLength={20} maxLength={2000}/></label></>}
 <label className="hidden" aria-hidden="true">Website<input name="website" tabIndex={-1} autoComplete="off"/></label>
 <label className="my-5 flex items-start gap-3 text-sm"><input name="consent" type="checkbox" required className="mt-1"/>{kind==='mentor'?t('Ich möchte, dass meine Angaben zur Bearbeitung meiner Bewerbung verwendet werden.','I agree to my details being used to process my application.'):t('Ich möchte den Newsletter erhalten und kann mich jederzeit abmelden.','I want to receive the newsletter and can unsubscribe at any time.')}</label><a href="/datenschutz" className="mb-4 block text-xs underline">{t('Datenschutzhinweise','Privacy information (German)')}</a>
 {!demo&&<Turnstile key={attempt} onToken={callback}/>}<Button className="mt-5" disabled={busy||(!demo&&!token)}>{busy?t('Wird verarbeitet …','Processing …'):demo?t('Ablauf simulieren','Simulate this step'):t('Anfrage absenden','Submit request')}</Button>
 </form>:<div className="mt-5 rounded-xl bg-secondary p-5">{demo?<><p className="text-sm">{kind==='mentor'?t('Demo-Bewerbung eingegangen. Noch kein veröffentlichtes Profil.','Demo application received. No profile has been published.'):stage==='pending'?t('Demo-Posteingang: Bitte bestätige deine Newsletter-Anmeldung. Es wurde keine E-Mail versendet.','Demo inbox: please confirm your subscription. No email was sent.'):stage==='confirmed'?t('Demo-Anmeldung bestätigt.','Demo subscription confirmed.'):t('Demo-Abmeldung abgeschlossen.','Demo unsubscribe completed.')}</p>{kind==='newsletter'&&stage==='pending'&&<Button className="mt-4" onClick={()=>setStage('confirmed')}>{t('Demo-Anmeldung bestätigen','Confirm demo subscription')}</Button>}{kind==='newsletter'&&stage==='confirmed'&&<Button variant="outline" className="mt-4" onClick={()=>setStage('unsubscribed')}>{t('Demo-Abmeldung testen','Try demo unsubscribe')}</Button>}</>:null}<Button variant="ghost" className="mt-4" onClick={()=>{setStage('form');setNotice('');}}>{t('Zurück zum Formular','Back to form')}</Button></div>}
 <p role="status" className="mt-4 text-sm">{notice}</p></section>;
}
