import { OriginalMentorExamples } from '@/components/mentors/original-mentor-examples';
import { TravelInspiration } from '@/components/home/travel-inspiration';
import { TravelBenefits, TeamInvitation, PlanningInvitation } from '@/components/home/personal-sections';
import { DestinationCards } from '@/components/home/destination-cards';
import { DestinationHero } from '@/components/home/destination-hero';
import Link from 'next/link';
import { ArrowUpRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { FeaturedMentors } from '@/components/home/featured-mentors';
export const metadata = {title:'Individuell reisen. Lokal verbunden.',description:'Stay Safe & Brave verbindet Individualreisende mit persönlichen Local Mentoren in Südafrika. Entdecke lokale Perspektiven vor und während deiner Reise.'};
export default function HomePage(){return <>
 <DestinationHero />
 <DestinationCards />
 <TravelBenefits />
 <section className="section-space border-t"><div className="page-shell"><div className="mb-9 flex flex-col sm:flex-row sm:items-end justify-between gap-4"><div><p className="eyebrow mb-3">Local Mentoren</p><h2 className="editorial-title section-title">Wen möchtest du kennenlernen?</h2></div><Link href="/mentors" className="quiet-link text-sm">Alle Local Mentoren<ArrowUpRight className="h-4 w-4"/></Link></div><FeaturedMentors/><OriginalMentorExamples preview/></div></section>
 <TravelInspiration />
 <TeamInvitation />
 <section id="so-funktionierts" className="section-space page-shell"><p className="eyebrow mb-3">So funktioniert’s</p><h2 className="editorial-title section-title mb-10">Von deiner Idee zum lokalen Kontakt.</h2><ol className="grid gap-8 md:grid-cols-3">{[['Kennenlernen','Entdecke Profile, Interessen und Sprachen. Finde einen Menschen, der zu dir passt.'],['Anfrage stellen','Wähle deine Unterstützung und teile deinen gewünschten Reisezeitraum.'],['Gemeinsam abstimmen','Kläre Umfang und Details. Eine Anfrage ist noch keine bestätigte Buchung.']].map(([title,text],i)=><li key={title} className="border-t pt-5"><span className="text-sm text-primary">0{i+1}</span><h3 className="mt-5 text-xl">{title}</h3><p className="mt-3 text-muted-foreground leading-relaxed">{text}</p></li>)}</ol></section>
 <section className="section-space page-shell grid gap-8 md:grid-cols-2"><div><p className="eyebrow mb-3">Unterstützung, die zu dir passt</p><h2 className="editorial-title section-title">Welche Begleitung<br/>passt zu deiner Reise?</h2></div><div><p className="text-muted-foreground leading-relaxed">Die Leistungen und Preise unserer Begleitpakete werden noch abgestimmt. Bei verfügbaren Profilen kannst du einen Local Mentor kennenlernen und eine Anfrage stellen. Online-Zahlungen sind derzeit nicht verfügbar.</p><Link href="/pakete-preise" className="quiet-link mt-5">Zum aktuellen Angebotsstand<ArrowUpRight className="h-4 w-4"/></Link></div></section>
 <section className="page-shell pb-14"><div className="rounded-3xl bg-secondary/60 p-6 sm:p-10 flex flex-col md:flex-row items-start md:items-center justify-between gap-6"><div className="max-w-xl"><p className="eyebrow mb-3">Erlebe die Buchung als Demo</p><h2 className="editorial-title section-title">Von der Paketauswahl bis zur Ankunft.</h2><p className="mt-4 text-sm leading-relaxed text-muted-foreground">Begleite Anna auf ihrer ersten Alleinreise: Paket wählen, Warenkorb prüfen, Zahlung simulieren und die eigene Reiseübersicht entdecken. Ohne echte Kosten.</p></div><Button asChild size="lg"><Link href="/demo">Demo-Reise starten<ArrowUpRight aria-hidden="true" /></Link></Button></div></section>
 <PlanningInvitation />
 <section className="page-shell pb-16"><div className="grid gap-8 md:grid-cols-2"><div><p className="eyebrow mb-3">Gut zu wissen</p><h2 className="editorial-title section-title">Fragen zur<br/>persönlichen Begleitung.</h2><Link href="/sicherheitsrichtlinien" className="quiet-link mt-5 text-sm">Mehr über Vertrauen & Begleitung</Link></div><div>{[['Organisiere ich meine Reise selbst?','Ja. Du entscheidest über deine Reise. Die persönliche Unterstützung durch einen Local Mentor wird gemeinsam abgestimmt.'],['Ist eine Anfrage schon eine Buchung?','Nein. Der gewünschte Zeitraum und die Begleitung müssen zunächst bestätigt werden. Leistungen und Preise sind derzeit noch in Abstimmung.'],['Woran erkenne ich geprüfte Profile?','Vertrauensmerkmale erscheinen auf dem jeweiligen Profil, wenn entsprechende Angaben hinterlegt sind. Eine Begleitung ist keine Sicherheitsgarantie.']].map(([q,a])=><details key={q} className="border-b py-5"><summary className="cursor-pointer font-medium">{q}</summary><p className="mt-4 text-sm leading-relaxed text-muted-foreground">{a}</p></details>)}</div></div></section>
 <section className="bg-[#e9d7cb] py-14 sm:py-20"><div className="page-shell flex flex-col md:flex-row items-start md:items-center justify-between gap-7"><h2 className="editorial-title section-title">Lerne die Local Mentoren<br/>in Südafrika kennen.</h2><Button asChild size="lg"><Link href="/mentors">Local Mentor finden<ArrowUpRight/></Link></Button></div></section>
 </>}
