import type { MentorDTO } from '@/lib/dtos';
import Link from 'next/link';
import { ArrowUpRight, MapPin, CheckCircle2, Star } from 'lucide-react';
import { ContentImage } from '@/components/ui/content-image';
export function MentorCard({mentor}:{mentor:MentorDTO}){
 const name=mentor.firstName||'Local Mentor';const fullName=[mentor.firstName,mentor.lastName].filter(Boolean).join(' ')||name;
 const rating=typeof mentor.averageRating==='number' && mentor.averageRating>0 && mentor.averageRating<=5 && (mentor.reviewCount||0)>0;
 return <article className="group flex h-full flex-col min-w-0"><Link href={`/mentors/${mentor.id}`} aria-label={`Profil von ${fullName} ansehen`} className="relative block overflow-hidden rounded-2xl"><ContentImage src={mentor.profilePictureUrl} alt={`Porträt von ${fullName}`} fallback={`Porträt von ${name} noch nicht verfügbar`} className="aspect-[4/3] w-full transition-transform duration-300 group-hover:scale-[1.02]"/>{mentor.verificationStatus==='verified'&&<span className="absolute left-3 bottom-3 inline-flex items-center gap-1 rounded-full bg-background px-3 py-1.5 text-xs font-medium"><CheckCircle2 className="h-3.5 w-3.5"/>Verifiziert</span>}</Link><div className="py-5 flex flex-col flex-1"><div className="flex items-start justify-between gap-3"><h2 className="text-2xl"><Link href={`/mentors/${mentor.id}`}>{name}</Link></h2>{rating&&<span className="flex items-center gap-1 text-sm"><Star className="h-3.5 w-3.5"/>{mentor.averageRating!.toFixed(1)}<span className="text-muted-foreground">({mentor.reviewCount})</span></span>}</div><p className="mt-1 flex items-center gap-1 text-sm text-muted-foreground"><MapPin className="h-3.5 w-3.5"/>{mentor.location||'Ort nicht angegeben'}</p>{mentor.bio&&<p className="mt-4 text-sm leading-relaxed line-clamp-3 text-muted-foreground">{mentor.bio}</p>}<div className="mt-4 flex flex-wrap gap-2">{(mentor.areasOfExpertise||[]).slice(0,2).map(t=><span key={t} className="rounded-full border px-2.5 py-1 text-xs">{t}</span>)}</div>{mentor.languages?.length>0&&<p className="mt-3 text-sm text-muted-foreground">{mentor.languages.join(' · ')}</p>}<Link className="mt-auto pt-5 text-sm font-medium flex items-center justify-between" href={`/mentors/${mentor.id}`}>Lerne {name} kennen<ArrowUpRight className="h-4 w-4"/></Link></div></article>;
}
